list: $/harryfurnish/philterplugin/models/image/columns.yaml
modelClass: HarryFurnish\Philterplugin\Models\Image
title: Image
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'harryfurnish/philterplugin/image/update/:id'
