title: Tags
modelClass: HarryFurnish\Philterplugin\Models\Tag
list: $/harryfurnish/philterplugin/models/tag/columns.yaml
recordUrl: 'harryfurnish/philterplugin/tags/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
